projeto-de-instrucao-tecnologica/learning-python

- .gitignore
- README.md
- Updating README;
- Uploading Structure;
- Updating .gitignore;
> :memo: Setting up the repo info.

- README.md
- lists/list_template_basic.ipynb
- Removing .placeholder file;
- Adding a list template with basic difficulty;
- Updating ReadMe;
> :bulb: Adding initial lists

- README.md
- single_questions/question_template_basic.ipynb
- Removing .placeholder file;
- Adding a question template with basic difficulty;
- Updating ReadMe;
> :bulb: Adding a Basic Difficulty Question Template.

- lists/list_template_intermediary.ipynb
> :bulb: Adding a intermediary template list.

- single_questions/sub_baby.ipynb
Adding a subtraction question with a baby difficulty
> :bulb: Adding baby subtraction question

- single_questions/mult_baby.ipynb
Adding a multiplication question with a baby difficulty
> :bulb: Adding baby multiplication question

- single_questions/question_count_list_baby.ipynb
Adding a count-list with basic difficulty.
> :bulb: Adding basic count-list question.

- single_questions/question_is-divisible_basic.ipynb
Adding a is divisible question with basic difficulty
> :bulb: Adding basic is-divisible question.

- single_questions/question_split_by_space_basic.ipynb
Adding a split by space question with  basic difficulty.
> :bulb: Adding basic split_by_space question.

- single_questions/question_div_baby.ipynb
Adding a division question with baby difficulty.
> :bulb: Adding baby division question.

- single_questions/question_concat_baby.ipynb
Adding concatenation question with baby difficulty.
> :bulb: Adding baby concatenation question.

- single_questions/question_template_basic.ipynb
updating question basic template.
> :repeat: updating question basic template.

- lists/list_template_basic.ipynb
> :repeat: updating basic list template

- single_questions/question_exponential_baby.ipynb
Adding a exponential question with baby difficulty.
> :bulb: adding question exponential baby

- single_questions/question_start_end_list_baby.ipynb
Adding a question with baby difficulty.
> :bulb: adding question start end list baby

- lists/list_template_baby.ipynb
Adding a new list template with baby difficulty.
> :bulb: Adding a new baby list template.

- single_questions/question_average_baby.ipynb
Adding a new question with baby difficulty.
> :bulb: Adding a new baby question.

- single_questions/question_odd-or-even_baby.ipynb
Adding a baby question with baby difficulty.
> :bulb: adding question_odd-or-even_baby.

- lists/list_template_baby.ipynb
Adding a question to a baby list.
> :bulb: adding a baby question to list.

- lists/list_template_baby.ipynb
Adding a baby question to baby list.
> :bulb: adding the count list baby question to list.

- lists/list_calculator_baby.ipynb
Adding a new list focused in calculation.
> :bulb: Adding the new calc baby list.

- single_questions/question_sum_baby.ipynb
> :bulb: adding sum question.

- lists/list_calculator_baby.ipynb
- single_questions/question_sum_baby.ipynb
Improving calc list with sum question
> Improving calc list

- single_questions/question_number-inverter_basic.ipynb
Adding a new question that uses repetition structure to invert an int number sequence.
> Adding number inverter new basic question

- single_questions/question_gas-spent-simulation_intermediary.ipynb
Adding an intermediary question that requires Class concepts.
> Adding new question based in classes intermediary
